### ISSUE TITLE
是否可以增加天气逐时预报功能？

### ISSUE THREAD

**Issue by ChellyL** [daya0576/he-weather-bot#10]
开发者你好，我用了下bot觉得挺好用的，
但我觉得如果只实时播报当天和明天天气，功能有点少，能不能加上未来几小时天气预报？
比如我在早上8点查一下当前天气，只会告诉我一整天的天气范围，如果能加上当前天气以及10、12点的天气预报，感觉更实用一些
~~不过我在和风天气找到了逐时天气的api但是获取后只返回403，不知道是不是接口出问题了（原来是因为我没有升级成开发者）~~

**Comment by daya0576** [comment]
你好，

定时「实时播报」正如名字，查询的是实时最准确的当天天气，如果加上未来几小时天气个人感觉意义不是太大。 
但是会考虑添加入口：支持主动查询未来3小时、未来3天天气，不知是否能满足您的需求～

多谢

**Comment by ChellyL** [comment]
如果能增加未来3小时和3天天气的查询功能我觉得就非常够用了！非常感谢回复！

**Comment by daya0576** [comment]
hi，最近 6 小时天气预报已上线：
![image](https://user-images.githubusercontent.com/6239652/147388089-498a0cb7-f826-4545-8871-ac9984e35e8b.png)

欢迎试用～

**Comment by ChellyL** [comment]
感谢提醒~很实用！
