### ISSUE TITLE
/help处的联系方式不正常

### ISSUE THREAD

**Issue by greenredstone** [daya0576/he-weather-bot#6]
![Screenshot_2021-06-30-22-15-35-504_nekox messenger](https://user-images.githubusercontent.com/49808960/123976810-11a70100-d984-11eb-903b-ee179de0c48f.png)
![Screenshot_2021-06-30-22-15-43-501_nekox messenger](https://user-images.githubusercontent.com/49808960/123976823-14a1f180-d984-11eb-9922-166a0cccc381.png)

**Comment by daya0576** [comment]
多谢提醒，fixed
